import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { SidebarProvider } from "@/components/navbar/SidebarContext";
import { Toaster } from "@/components/ui/toaster";
import { RouteGuard } from "@/core/routes/routeGuard";
import { Providers } from "@/core/store/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Track Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers>
          {/* <RouteGuard> */}
            <SidebarProvider>
              <Toaster />
              {children}
            </SidebarProvider>
          {/* </RouteGuard> */}
        </Providers>
      </body>
    </html>
  );
}
