export enum ApiRoutesEnum {
  API_CHECK = "API_CHECK",
  UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE",
  ADD_USER_PROFILE = "ADD_USER_PROFILE",
  GET_USER_PROFILE_LIST = "GET_USER_PROFILE_LIST",
  GET_USER_PROFILE = "GET_USER_PROFILE",
  UPDATE_VENDOR_PROFILE = "UPDATE_VENDOR_PROFILE",
  ADD_VENDOR_PROFILE = "ADD_VENDOR_PROFILE",
  GET_VENDOR_PROFILE_LIST = "GET_VENDOR_PROFILE_LIST",
  GET_VENDOR_PROFILE = "GET_VENDOR_PROFILE",
}


